table Review_Run
	lineageTag: 4f73e111-c9a8-4f99-b247-565210aeee6d

	column RunID
		dataType: string
		summarizeBy: none
		sourceColumn: RunID
		lineageTag: 825afcfd-1499-4b89-8b0d-23ff275f13ea

	column Entity
		dataType: string
		summarizeBy: none
		sourceColumn: Entity
		lineageTag: c53229d6-9a94-4c05-a7f8-96553bdc687a

	column Tenant
		dataType: string
		summarizeBy: none
		sourceColumn: Tenant
		lineageTag: 6385f6d7-2831-4d42-8ea1-c67e850e5669

	column Period
		dataType: string
		summarizeBy: none
		sourceColumn: Period
		lineageTag: 5134baa8-3af3-449d-bb7e-d6ff6ed55297

	column Basis
		dataType: string
		summarizeBy: none
		sourceColumn: Basis
		lineageTag: 9e5ec263-7211-420c-9fc8-7d0f7df3c969

	column Currency
		dataType: string
		summarizeBy: none
		sourceColumn: Currency
		lineageTag: 01b14056-581a-4ad7-9556-1da16ea7e4b6

	column CloseStatus
		dataType: string
		summarizeBy: none
		sourceColumn: CloseStatus
		lineageTag: e4fdd0d3-3dbc-4333-9de5-36dab1a56691

	column ReadinessStatus
		dataType: string
		summarizeBy: none
		sourceColumn: ReadinessStatus
		lineageTag: b9e5d8c0-3430-43ea-ac71-a9a678d5f091

	column PriorPeriod
		dataType: string
		summarizeBy: none
		sourceColumn: PriorPeriod
		lineageTag: 9fc8a6d4-1584-40b8-bcc5-04e53c082b76

	column AbsoluteThreshold
		dataType: string
		summarizeBy: none
		sourceColumn: AbsoluteThreshold
		lineageTag: 54231bca-2249-4bdb-8823-96434e79bb08

	column PercentageThreshold
		dataType: string
		summarizeBy: none
		sourceColumn: PercentageThreshold
		lineageTag: 49590497-e06e-44a0-b916-59ab2c4f2a4e

	column ControlsNotRun
		dataType: string
		summarizeBy: none
		sourceColumn: ControlsNotRun
		lineageTag: f439aa9e-01dc-4760-8fdb-5d415addee5b

	column ReadinessControlsNotRun
		dataType: string
		summarizeBy: none
		sourceColumn: ReadinessControlsNotRun
		lineageTag: d7c05017-6d64-4ab3-b81d-8e73a69a9a8b

	column Acknowledgement
		dataType: string
		summarizeBy: none
		sourceColumn: Acknowledgement
		lineageTag: 78e9f561-29ec-4164-a39d-68826c70d6bf

	column UnmappedExceptions
		dataType: string
		summarizeBy: none
		sourceColumn: UnmappedExceptions
		lineageTag: ee92cfe6-6306-4396-bae9-73a3e868c330

	column SourceTBHash
		dataType: string
		summarizeBy: none
		sourceColumn: SourceTBHash
		lineageTag: ede7714a-bafe-43ab-babe-7108951e62e1

	column SourceGLHash
		dataType: string
		summarizeBy: none
		sourceColumn: SourceGLHash
		lineageTag: 781f6db0-1bf5-4121-9034-27a9fd31ddcd

	column Verification
		dataType: string
		summarizeBy: none
		sourceColumn: Verification
		lineageTag: 5ff80e75-7d01-45ce-8c8f-d76e314469f6

	column Boundary
		dataType: string
		summarizeBy: none
		sourceColumn: Boundary
		lineageTag: fdaad550-8d04-4291-91d7-98224baa88ca

	column AbsoluteThresholdDisplay
		dataType: string
		summarizeBy: none
		sourceColumn: AbsoluteThresholdDisplay
		lineageTag: 9a15b880-ab44-4622-aaf7-1e2cf8b474c9

	column ControlsNotRunDisplay
		dataType: string
		summarizeBy: none
		sourceColumn: ControlsNotRunDisplay
		lineageTag: 9920038f-5f78-4901-b5ae-a1d8922e1a39

	partition Review_Run = m
		mode: import
		source =
			let
				Source = Table.PromoteHeaders(Csv.Document(File.Contents(SampleFolder & "/sample-review-run.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]),
				Schema = if Table.ColumnNames(Source) <> {"RunID", "Entity", "Tenant", "Period", "Basis", "Currency", "CloseStatus", "ReadinessStatus", "PriorPeriod", "AbsoluteThreshold", "PercentageThreshold", "ControlsNotRun", "ReadinessControlsNotRun", "Acknowledgement", "UnmappedExceptions", "SourceTBHash", "SourceGLHash", "Verification", "Boundary"} then error "Review fixture schema differs." else Source,
				Required = Fx_RequireRows(Schema, {"RunID", "Entity", "Period", "Basis", "Currency"}, {"RunID"}, "Review_Run"),
				Context = if Table.RowCount(Required) = 0 or Table.RowCount(Table.SelectRows(Required, each [Entity] <> "ENT001" or [Period] <> "2024-09-30" or [Currency] <> "AUD" or [Basis] <> "Accrual, single entity gross ledger" or Text.Length([RunID]) <> 64)) > 0 then error "Review fixture context differs." else Required,
				Typed = Table.TransformColumnTypes(Context, List.Transform(Table.ColumnNames(Context), each {_, type text})),
				Display = List.Accumulate({"AbsoluteThreshold"}, Typed, (state, field) => Table.AddColumn(state, field & "Display", each Fx_MoneyDisplay(Record.Field(_, field)), type text)),
				Labels = [account_mapping="Account mapping", balance_policy="Balance policy", subledger="Subledger", calculation_evidence="Calculation evidence"],
				Controls = Table.AddColumn(Display, "ControlsNotRunDisplay", each Text.Combine(List.Transform(Text.Split([ControlsNotRun], "; "), (code) => Record.FieldOrDefault(Labels, code, code)), "; "), type text)
			in
				if not Table.IsEmpty(Table.SelectRowsWithErrors(Controls)) then error Error.Record("Review amount", "Invalid decimal display value", "Correct the source CSV before refreshing.") else Controls
