table Review_Exception
	lineageTag: 2301fe2f-869a-4cb8-bf1d-0415dab13b7c

	/// One only when a single finding is explicitly selected by account or exception identity.
	measure 'Finding selection present' = IF(HASONEVALUE(Review_Exception[ExceptionKey]) && (ISFILTERED(Review_Exception[Account]) || ISFILTERED(Review_Exception[ExceptionKey])), 1, 0)
		formatString: 0
		displayFolder: Review details

	/// The complete source action for one selected finding; prompts for selection otherwise.
	measure 'Finding Action' = IF([Finding selection present] = 1, SELECTEDVALUE(Review_Exception[Action]), "Select a single finding to see its full details.")
		displayFolder: Review details

	/// The complete source question for one selected finding; blank otherwise.
	measure 'Finding Question' = IF([Finding selection present] = 1, SELECTEDVALUE(Review_Exception[Question]), BLANK())
		displayFolder: Review details

	/// The complete source reason for one selected finding; blank otherwise.
	measure 'Finding Reason' = IF([Finding selection present] = 1, SELECTEDVALUE(Review_Exception[Reason]), BLANK())
		displayFolder: Review details

	/// The complete source evidence request for one selected finding; blank otherwise.
	measure 'Finding Evidence requested' = IF([Finding selection present] = 1, SELECTEDVALUE(Review_Exception[EvidenceRequested]), BLANK())
		displayFolder: Review details

	/// The source evidence state for one selected finding; blank otherwise.
	measure 'Finding Evidence state' = IF([Finding selection present] = 1, SELECTEDVALUE(Review_Exception[EvidenceState]), BLANK())
		displayFolder: Review details

	column RunID
		dataType: string
		summarizeBy: none
		sourceColumn: RunID
		lineageTag: 2e670aeb-df93-4f58-bbd5-17431007d106

	column Entity
		dataType: string
		summarizeBy: none
		sourceColumn: Entity
		lineageTag: fa3481e5-13fc-4da5-801f-e5255e949a93

	column Tenant
		dataType: string
		summarizeBy: none
		sourceColumn: Tenant
		lineageTag: 15f370bc-56e5-4d3a-98d0-9c58d2469c8d

	column Period
		dataType: string
		summarizeBy: none
		sourceColumn: Period
		lineageTag: ce8d4f96-5b18-435a-a401-b3b54aae7b94

	column Basis
		dataType: string
		summarizeBy: none
		sourceColumn: Basis
		lineageTag: 6e04ccf1-0cbe-405f-a00a-7e76c9658c69

	column Currency
		dataType: string
		summarizeBy: none
		sourceColumn: Currency
		lineageTag: 696790ef-511e-44a0-a6ef-504b6dcc28ea

	column ExceptionKey
		dataType: string
		summarizeBy: none
		sourceColumn: ExceptionKey
		lineageTag: 1e637b74-c68f-4c41-a30b-4674fb7c676c

	column Control
		dataType: string
		summarizeBy: none
		sourceColumn: Control
		lineageTag: 593e5642-98b4-4316-b926-fe258db08d39

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 1af55b60-cf03-4fba-9efc-da5c4758b9e8

	column AccountID
		dataType: string
		summarizeBy: none
		sourceColumn: AccountID
		lineageTag: abb0cefe-6e40-41a1-9b4e-604ea89789a9

	column Account
		dataType: string
		summarizeBy: none
		sourceColumn: Account
		lineageTag: 6513d5e9-3321-4f2e-afaf-b62ef3ac5f93

	column Current
		dataType: string
		summarizeBy: none
		sourceColumn: Current
		lineageTag: 83c16317-e6c8-4f18-b1f7-8ae6c08063df

	column Prior
		dataType: string
		summarizeBy: none
		sourceColumn: Prior
		lineageTag: bc7970a6-bc96-4511-a284-2f5da3b98884

	column Difference
		dataType: string
		summarizeBy: none
		sourceColumn: Difference
		lineageTag: d9fbeaa8-6eea-47c0-b436-78488c85936a

	column Threshold
		dataType: string
		summarizeBy: none
		sourceColumn: Threshold
		lineageTag: 0225ce96-3724-4fcc-af54-7599acf4b64e

	column Reason
		dataType: string
		summarizeBy: none
		sourceColumn: Reason
		lineageTag: ac9894aa-b6ae-4eae-90e5-4c39c18e6fd7

	column Action
		dataType: string
		summarizeBy: none
		sourceColumn: Action
		lineageTag: 98711a4f-b7af-422d-b45f-80f1ada7f4fe

	column Question
		dataType: string
		summarizeBy: none
		sourceColumn: Question
		lineageTag: d848ae90-0b8e-40ed-bd47-e81b528494b8

	column EvidenceRequested
		dataType: string
		summarizeBy: none
		sourceColumn: EvidenceRequested
		lineageTag: 10fefd44-5547-4cab-9d52-8cda649e2b07

	column EvidenceState
		dataType: string
		summarizeBy: none
		sourceColumn: EvidenceState
		lineageTag: a3ebdd77-5137-45bd-a4b3-2d557ad07f2a

	column CurrentDisplay
		dataType: string
		summarizeBy: none
		sourceColumn: CurrentDisplay
		lineageTag: 02b64444-de45-4f7f-9570-f87184f052ce

	column PriorDisplay
		dataType: string
		summarizeBy: none
		sourceColumn: PriorDisplay
		lineageTag: ea0a9dec-efba-4d59-8a6d-b5c275dd54e1

	column DifferenceDisplay
		dataType: string
		summarizeBy: none
		sourceColumn: DifferenceDisplay
		lineageTag: b8a91c2e-8175-4968-9dd1-8f04f88d50df

	partition Review_Exception = m
		mode: import
		source =
			let
				Source = Table.PromoteHeaders(Csv.Document(File.Contents(SampleFolder & "/sample-review-exceptions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]),
				Schema = if Table.ColumnNames(Source) <> {"RunID", "Entity", "Tenant", "Period", "Basis", "Currency", "ExceptionKey", "Control", "Status", "AccountID", "Account", "Current", "Prior", "Difference", "Threshold", "Reason", "Action", "Question", "EvidenceRequested", "EvidenceState"} then error "Review fixture schema differs." else Source,
				Required = Fx_RequireRows(Schema, {"RunID", "Entity", "Tenant", "Period", "Basis", "Currency", "ExceptionKey"}, {"ExceptionKey"}, "Review_Exception"),
				Context = if Table.RowCount(Required) = 0 or Table.RowCount(Table.SelectRows(Required, each [Entity] <> "ENT001" or [Period] <> "2024-09-30" or [Currency] <> "AUD" or [Basis] <> "Accrual, single entity gross ledger" or Text.Length([RunID]) <> 64)) > 0 then error "Review fixture context differs." else Required,
				RunContextColumns = {"RunID", "Entity", "Tenant", "Period", "Basis", "Currency"},
				Unmatched = Table.NestedJoin(Context, RunContextColumns, Table.SelectColumns(Review_Run, RunContextColumns), RunContextColumns, "RunMatch", JoinKind.LeftAnti),
				Validated = if not Table.IsEmpty(Unmatched) then error "Review exception projection differs." else Context,
				Typed = Table.TransformColumnTypes(Validated, List.Transform(Table.ColumnNames(Validated), each {_, type text})),
				Display = List.Accumulate({"Current", "Prior", "Difference"}, Typed, (state, field) => Table.AddColumn(state, field & "Display", each Fx_MoneyDisplay(Record.Field(_, field)), type text))
			in
				if not Table.IsEmpty(Table.SelectRowsWithErrors(Display)) then error Error.Record("Review amount", "Invalid decimal display value", "Correct the source CSV before refreshing.") else Display
