table Review_Evidence
	lineageTag: d466b4e0-2b03-4db0-a7d5-d5e854fbee64

	/// Evidence rows appear only for one explicitly selected exception.
	measure 'Evidence selection present' = IF(HASONEVALUE(Review_Exception[ExceptionKey]) && ISFILTERED(Review_Exception[ExceptionKey]) && COUNTROWS(Review_Evidence) > 0, 1, BLANK())
		formatString: 0
		displayFolder: Review evidence

	column RunID
		dataType: string
		summarizeBy: none
		sourceColumn: RunID
		lineageTag: 8fb5d671-9064-42d1-885b-6d605ed23183

	column Entity
		dataType: string
		summarizeBy: none
		sourceColumn: Entity
		lineageTag: ac02d6a2-3841-4a9d-aed1-f77a14d5046d

	column Tenant
		dataType: string
		summarizeBy: none
		sourceColumn: Tenant
		lineageTag: 16406c05-35bb-428b-8782-c89fe9f7da1d

	column Period
		dataType: string
		summarizeBy: none
		sourceColumn: Period
		lineageTag: 405067a4-a1b8-484d-97b2-e95e8af2e9f6

	column Basis
		dataType: string
		summarizeBy: none
		sourceColumn: Basis
		lineageTag: 6a694098-7d7f-4b72-9205-f2232906d20f

	column Currency
		dataType: string
		summarizeBy: none
		sourceColumn: Currency
		lineageTag: cf34250e-d543-4fcd-b3ef-8fd24296e2da

	column ExceptionKey
		dataType: string
		summarizeBy: none
		sourceColumn: ExceptionKey
		lineageTag: db56debf-1b80-4ef8-964f-494b7ffa9acb

	column AccountID
		dataType: string
		summarizeBy: none
		sourceColumn: AccountID
		lineageTag: f7186a90-6f62-4355-ba67-5aaa9d9a3768

	column TransactionID
		dataType: string
		summarizeBy: none
		sourceColumn: TransactionID
		lineageTag: fae8687a-24c3-4b48-8e18-ea3e027aaee2

	column Date
		dataType: string
		summarizeBy: none
		sourceColumn: Date
		lineageTag: d2a115ed-3ab0-4f9d-860d-2985207b5664

	column Reference
		dataType: string
		summarizeBy: none
		sourceColumn: Reference
		lineageTag: 16372f67-2f89-4f18-a61a-d5d4124545db

	column Description
		dataType: string
		summarizeBy: none
		sourceColumn: Description
		lineageTag: fe974051-42a1-43ee-bc8e-8dc9ecd3e6c5

	column Amount
		dataType: string
		summarizeBy: none
		sourceColumn: Amount
		lineageTag: 8fc833dd-45a1-43fe-8988-d66e20954c58

	column AmountDisplay
		dataType: string
		summarizeBy: none
		sourceColumn: AmountDisplay
		lineageTag: e1f267a4-09c7-47e3-821e-55dcd6cf3629

	partition Review_Evidence = m
		mode: import
		source =
			let
				Source = Table.PromoteHeaders(Csv.Document(File.Contents(SampleFolder & "/sample-review-evidence.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]),
				Schema = if Table.ColumnNames(Source) <> {"RunID", "Entity", "Tenant", "Period", "Basis", "Currency", "ExceptionKey", "AccountID", "TransactionID", "Date", "Reference", "Description", "Amount"} then error "Review fixture schema differs." else Source,
				Required = Fx_RequireRows(Schema, {"RunID", "Entity", "Tenant", "Period", "Basis", "Currency", "ExceptionKey", "AccountID", "TransactionID"}, {"ExceptionKey", "TransactionID"}, "Review_Evidence"),
				Context = if Table.RowCount(Table.SelectRows(Required, each [Entity] <> "ENT001" or [Period] <> "2024-09-30" or [Currency] <> "AUD" or [Basis] <> "Accrual, single entity gross ledger" or Text.Length([RunID]) <> 64)) > 0 then error "Review fixture context differs." else Required,
				FindingColumns = {"ExceptionKey", "RunID", "Entity", "Tenant", "Period", "Basis", "Currency", "AccountID"},
				Unmatched = Table.NestedJoin(Context, FindingColumns, Table.SelectColumns(Review_Exception, FindingColumns), FindingColumns, "FindingMatch", JoinKind.LeftAnti),
				Validated = if not Table.IsEmpty(Unmatched) then error "Review evidence projection differs." else Context,
				Reconciled = Table.SelectRows(Review_Exception, each [EvidenceState] = "Journal rows reconciled"),
				Unavailable = Table.NestedJoin(Validated, FindingColumns, Table.SelectColumns(Reconciled, FindingColumns), FindingColumns, "ReconciledMatch", JoinKind.LeftAnti),
				Admitted = if not Table.IsEmpty(Unavailable) then error "Unavailable findings cannot carry journal evidence." else Validated,
				RawAmounts = Table.AddColumn(Admitted, "AmountDisplay", each Fx_MoneyDisplay([Amount]), type text),
				CheckedAmounts = if not Table.IsEmpty(Table.SelectRowsWithErrors(RawAmounts)) or not Table.IsEmpty(Table.SelectRows(RawAmounts, each [AmountDisplay] = null)) then error Error.Record("Review amount", "Invalid decimal display value", "Correct the source CSV before refreshing.") else RawAmounts,
				Actual = Table.AddColumn(CheckedAmounts, "ValidationAmount", each Currency.From([Amount], "en-AU"), Currency.Type),
				AccountMap = #table(type table [AccountCode=text, AccountID=text], {
					{"100", "fixture-account-10"}, {"110", "fixture-account-20"}, {"120", "fixture-account-30"},
					{"180", "fixture-account-40"}, {"200", "fixture-account-50"}, {"210", "fixture-account-60"},
					{"250", "fixture-account-70"}, {"300", "fixture-account-110"}, {"310", "fixture-account-120"},
					{"320", "fixture-account-130"}, {"330", "fixture-account-140"}, {"380", "fixture-account-150"},
					{"400", "fixture-account-160"}, {"500", "fixture-account-210"}, {"510", "fixture-account-220"},
					{"600", "fixture-account-310"}, {"610", "fixture-account-320"}, {"620", "fixture-account-330"},
					{"650", "fixture-account-340"}, {"700", "fixture-account-410"}, {"710", "fixture-account-420"},
					{"750", "fixture-account-430"}, {"800", "fixture-account-510"}, {"805", "fixture-account-520"},
					{"810", "fixture-account-530"}, {"820", "fixture-account-540"}, {"830", "fixture-account-550"},
					{"880", "fixture-account-560"}, {"890", "fixture-account-570"}, {"895", "fixture-account-580"}
				}),
				Run = Review_Run{0},
				MonthEnd = Date.FromText(Run[Period], [Format="yyyy-MM-dd", Culture="en-AU"]),
				Ledger = Table.SelectRows(Source_Fact_GeneralLedger, each [EntityID] = Run[Entity] and [PostingDate] >= Date.StartOfMonth(MonthEnd) and [PostingDate] <= MonthEnd),
				MappedLedger = Table.NestedJoin(Ledger, {"AccountCode"}, AccountMap, {"AccountCode"}, "AccountMatch", JoinKind.LeftOuter),
				CompleteMap = if not Table.IsEmpty(Table.SelectRows(MappedLedger, each Table.RowCount([AccountMatch]) <> 1)) then error "Review ledger account mapping differs." else Table.ExpandTableColumn(MappedLedger, "AccountMatch", {"AccountID"}),
				WithTransaction = Table.AddColumn(CompleteMap, "TransactionID", each [JournalID] & ":" & Number.ToText([LineNumber], "0", "en-AU"), type text),
				WithDate = Table.AddColumn(WithTransaction, "Date", each Date.ToText([PostingDate], [Format="yyyy-MM-dd", Culture="en-AU"]), type text),
				LedgerRows = Table.RenameColumns(Table.SelectColumns(WithDate, {"AccountID", "TransactionID", "Date", "JournalID", "Description", "Amount"}), {{"JournalID", "Reference"}, {"Amount", "ValidationAmount"}}),
				FindingAmounts = Table.AddColumn(Reconciled, "ValidationDifference", each if [AccountID] = null or Text.Trim([AccountID]) = "" or Fx_MoneyDisplay([Difference]) = null then error "Reconciled finding requires an account and difference." else Currency.From([Difference], "en-AU"), Currency.Type),
				ExpectedGroups = Table.NestedJoin(FindingAmounts, {"AccountID"}, LedgerRows, {"AccountID"}, "ExpectedRows", JoinKind.LeftOuter),
				CompleteGroups = if not Table.IsEmpty(Table.SelectRowsWithErrors(ExpectedGroups)) or not Table.IsEmpty(Table.SelectRows(ExpectedGroups, each Table.IsEmpty([ExpectedRows]))) then error "Reconciled finding requires source journal rows." else ExpectedGroups,
				BalancedGroups = if not Table.IsEmpty(Table.SelectRows(CompleteGroups, each List.Sum([ExpectedRows][ValidationAmount], Precision.Decimal) <> [ValidationDifference])) then error "Reconciled finding difference does not tie to source journal rows." else CompleteGroups,
				Expected = Table.ExpandTableColumn(Table.SelectColumns(BalancedGroups, {"ExceptionKey", "ExpectedRows"}), "ExpectedRows", {"AccountID", "TransactionID", "Date", "Reference", "Description", "ValidationAmount"}),
				EvidenceColumns = {"ExceptionKey", "AccountID", "TransactionID", "Date", "Reference", "Description", "ValidationAmount"},
				Extra = Table.NestedJoin(Actual, EvidenceColumns, Expected, EvidenceColumns, "ExpectedMatch", JoinKind.LeftAnti),
				Missing = Table.NestedJoin(Expected, EvidenceColumns, Actual, EvidenceColumns, "ActualMatch", JoinKind.LeftAnti),
				Complete = if not Table.IsEmpty(Table.SelectRowsWithErrors(Actual)) or not Table.IsEmpty(Extra) or not Table.IsEmpty(Missing) then error "Review evidence journal population or detail differs from the source." else Admitted,
				Typed = Table.TransformColumnTypes(Complete, List.Transform(Table.ColumnNames(Complete), each {_, type text})),
				Display = List.Accumulate({"Amount"}, Typed, (state, field) => Table.AddColumn(state, field & "Display", each Fx_MoneyDisplay(Record.Field(_, field)), type text))
			in
				if not Table.IsEmpty(Table.SelectRowsWithErrors(Display)) then error Error.Record("Review amount", "Invalid decimal display value", "Correct the source CSV before refreshing.") else Display
